Adding pah_configure usable template
redhat-cop/ah_configuration pull request #104
Opened 2022-06-06 20:55 UTC by tonyreveal

### What does this PR do?
Adds a usable playbook, task files, and vars file for implementing ah_configuration.  Just populate the vars files and run the playbook with the correct tag(s).

### How should this be tested?
Linting has already been done.  Otherwise, populate the vars file(s) and run the pah_configure.yml playbook with an appropriate tag (documented in README).

### Is there a relevant Issue open for this?
Provide a link to any open issues that describe the problem you are solving.
N/A.

### Other Relevant info, PRs, etc.
Please provide link to other PRs that may be related (blocking, resolves, etc. etc.)

2022-06-06 21:20 UTC, sean-m-sullivan approved these changes
I like it, Its high time we had an example folder in Automation hub, I'm going to have Tom take a look over this before merging, but it Looks Awesome to me.

2022-06-06 21:33 UTC, djdanielsson reviewed
Also instead of including var files we could also just promote the idea of group_vars.

2022-06-06 21:33 UTC, djdanielsson commented on examples/pah_configure.yml
> +        - never
I don't think I understand this, why are there tags called 'never'?

2022-06-06 21:33 UTC, djdanielsson commented on examples/pah_configure.yml
> +      include_tasks: tasks/manage_groups.yml
why include a tasks file that imports a role? If I were to guess it has to do with tags, but this seems more complex then necessary for an example IMO.

2022-06-06 21:40 UTC, tonyreveal commented on examples/pah_configure.yml
> +        - never
This was a feature request by people who use my similar collection of playbook, tasks, and vars for controller_configuration.  They wanted the ability to run the playbook and select what objects to create rather that executing every collection role every time the playbook is executed.  This lets them only define a namespace or only define a user rather than running all collection roles just to add one user (for example).

2022-06-06 21:42 UTC, tonyreveal commented on examples/pah_configure.yml
> +      include_tasks: tasks/manage_groups.yml
So that the main playbook remains in a clean condition and just executes the task file.  And any customization that needs to occur happens in the individual task file.  For example, maybe I need to check namespaces for something, set some fact, and then run the namespace role from the ah_configuration collection.

2022-06-06 21:54 UTC, djdanielsson commented on examples/pah_configure.yml
> +        - never
interesting, while I can see a few people wanting this, I don't think it is for everyone. I am concerned about the complexity we are adding to an example in a way most people won't use.

2022-06-06 21:55 UTC, djdanielsson commented on examples/pah_configure.yml
> +      include_tasks: tasks/manage_groups.yml
It would be an interesting poll to see how many people do something like this over using group_vars and a simple playbook that calls imports roles directly.

2022-06-06 22:00 UTC, tonyreveal commented on examples/pah_configure.yml
> +        - never
What's so complex about it?  Just add your object definition to the correct vars file and run the playbook with the appropriate tag.

Think about it like this.  Do you want to wait 15 minutes for all of the other collections to finish running if all you wanted to do was a registry sync?  Or just execute the playbook with the regsync tag and get exactly the thing you wanted and nothing else?

2022-06-06 22:12 UTC, tonyreveal commented on examples/pah_configure.yml
> +      include_tasks: tasks/manage_groups.yml
Elaborate.  You lost me at group_vars.  AFAIK group_vars is for ansible inventories and this particular task that you've selected is for creating user groups in Automation Hub.

And like I said - it's also formatted this way for familiarity / consistency with the stuff I've already contributed to the controller_configuration collection.

2022-06-07 09:55 UTC, Tompage1994 requested changes

2022-06-07 09:55 UTC, Tompage1994 commented on examples/README.md
> +If executed with the `alltags` tag then the playbook will create all ojbects defined in all vars files in the appropriate order.
```suggestion
If executed with the `alltags` tag then the playbook will create all objects defined in all vars files in the appropriate order.
```

2022-06-07 09:55 UTC, Tompage1994 commented on examples/README.md
> +    absent_present
Not sure I like this as a name. Maybe something like `target_state`?

2022-06-07 09:55 UTC, Tompage1994 commented on examples/README.md
> +    ansible-playbook ah_configure.yaml --tags namespaces
Is it worth also using the `ansible-navigator` example here too since that is where the community is headed

2022-06-07 09:55 UTC, Tompage1994 commented on examples/README.md
> +An optional section for the role authors to include contact information, or a website (HTML is not allowed).
Can you add in your info here rather than leaving as the default text

2022-06-07 09:55 UTC, Tompage1994 commented on examples/README.md
> +Private Automation Hub Configuration
```suggestion
Private Automation Hub Configuration Example Playbook
```

2022-06-07 09:55 UTC, Tompage1994 commented on examples/pah_configure.yml
> +        - never
I'm not sure the tagging of never is really necessary here though? Surely if you just wanted to run the `manage_users` section you would just add the `users` tag and it would just include that and skip elsewhere. I'd expect not adding tags to run through everything rather than having to specify everything I do want it to run (unless I run with `--tags alltags` which is counterintuitive). I think removing that will end up with the same target state of being able to run a specific section but without the need of actually adding any tags if you don't want to.

2022-06-07 09:55 UTC, Tompage1994 commented on examples/tasks/manage_collection_publish.yml
> +    name: redhat_cop.ah_configuration.
```suggestion
    name: redhat_cop.ah_configuration
```

2022-06-07 09:55 UTC, Tompage1994 commented on examples/README.md
> +    ansible-playbook ah_configure.yml --tags alltags
```suggestion
    ansible-playbook pah_configure.yml --tags alltags
```

2022-06-07 09:55 UTC, Tompage1994 commented on examples/README.md
> +    ansible-playbook ah_configure.yaml --tags namespaces
```suggestion
    ansible-playbook pah_configure.yml --tags namespaces
```

2022-06-07 09:55 UTC, Tompage1994 commented on examples/vars/pah_vars.yml
> +ah_host:
```suggestion
ah_hostname:
```

2022-06-07 09:55 UTC, Tompage1994 commented on examples/README.md
> +    ah_host:
```suggestion
    ah_hostname:
```

2022-06-07 09:55 UTC, Tompage1994 commented on examples/pah_configure.yml
> +      include_vars: vars/pah_vars.yml
This wont ever get included if including a tag.

```suggestion
      include_vars: vars/pah_vars.yml
      tags:
        - always
```

2022-06-07 09:55 UTC, Tompage1994 commented on examples/vars/pah_vars.yml
> +validate_certs: false
```suggestion
ah_validate_certs: false
```

2022-06-07 09:55 UTC, Tompage1994 commented on examples/vars/ah_collection_namespaces.yml
> +ah_namespaces:
I think I would prefer example values in all of these. Enough that I could run it without changing anything (except perhaps the `pah_vars` and get a decent demo environment set up

2022-06-07 12:54 UTC, tonyreveal commented on examples/vars/pah_vars.yml
> +ah_host:
You sure?  The README for every role says `ah_host`.

2022-06-07 12:54 UTC, tonyreveal commented on examples/README.md
> +    ah_host:
You sure? The README for every role says ah_host.

2022-06-07 12:55 UTC, tonyreveal commented on examples/vars/pah_vars.yml
> +validate_certs: false
You sure? The README for every role says `validate_certs`.

2022-06-07 13:00 UTC, Tompage1994 commented on examples/README.md
> +    ah_host:
My bad. this should just be `ah_host`

2022-06-07 13:01 UTC, Tompage1994 commented on examples/vars/pah_vars.yml
> +validate_certs: false
Yeah, when I ran this it failed and I've just been through and checked and it should definitely be `ah_validate_certs`. I'll raise a doc PR to fix

2022-06-07 13:03 UTC, djdanielsson commented on examples/pah_configure.yml
> +      include_tasks: tasks/manage_groups.yml
it's fine, it seems I am in the minority here. Once the changes Tom requested are done I will merge the PR

2022-06-07 22:09 UTC, tonyreveal commented on examples/pah_configure.yml
> +        - never
Per [documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#selecting-or-skipping-tags-when-you-run-a-playbook), the default behavior is to run all tasks and ignore tags:

"--tags all - run all tasks, ignore tags (default behavior)".

I even tested this.  Hence the use of the never tag to ensure only the `always` and specific tag names execute when the playbook is run.

2022-06-07 22:18 UTC, tonyreveal commented on examples/pah_configure.yml
> +        - never
Here I've removed the `never` and `alltags` tags and run the playbook without specifying a tag.  You can see it still tries to run each task.  Of course it fails because I have no data in the vars :

` ansible-playbook tonyreveal/pah_config_template/pah_configure.yml

PLAY [Playbook to configure Private Automation Hub] ***************************************************************************************************

TASK [Include Vars] ***********************************************************************************************************************************
Tuesday 07 June 2022  18:16:39 -0400 (0:00:00.023)       0:00:00.023 **********
ok: [localhost]

TASK [Include task to manage private automation hub groups] *******************************************************************************************
Tuesday 07 June 2022  18:16:39 -0400 (0:00:00.043)       0:00:00.067 **********
included: /home/tony/Ansible/tonyreveal/pah_config_template/tasks/manage_groups.yml for localhost

TASK [Include vars] ***********************************************************************************************************************************
Tuesday 07 June 2022  18:16:39 -0400 (0:00:00.062)       0:00:00.129 **********
ok: [localhost]

TASK [redhat_cop.ah_configuration.group : Add Automation Hub group] ***********************************************************************************
Tuesday 07 June 2022  18:16:39 -0400 (0:00:00.032)       0:00:00.162 **********
fatal: [localhost]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: None. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}

PLAY RECAP ********************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
`

2022-06-07 22:24 UTC, tonyreveal commented on examples/pah_configure.yml
> +        - never
And then if I add the `never` tag back in and run the playbook with the `all` tag it will still skip the `never` tags, hence using the `alltags` tag:

```
ansible-playbook tonyreveal/pah_config_template/pah_configure.yml --tags all

PLAY [Playbook to configure Private Automation Hub] ***************************************************************************************************

TASK [Include Vars] ***********************************************************************************************************************************
Tuesday 07 June 2022  18:23:05 -0400 (0:00:00.028)       0:00:00.028 **********
ok: [localhost]

PLAY RECAP ********************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

2022-06-07 22:26 UTC, tonyreveal commented on examples/README.md
> +If executed with the `alltags` tag then the playbook will create all ojbects defined in all vars files in the appropriate order.
I don't see a change in this suggestion.

2022-06-07 22:28 UTC, tonyreveal commented on examples/README.md
> +    absent_present
The var name really doesn't matter to me.  I just figured `absent_present` was pretty self explanatory as to what is expected for a value.  I can change it to `target_state` if preferred.

2022-06-07 22:28 UTC, tonyreveal commented on examples/README.md
> +    ansible-playbook ah_configure.yaml --tags namespaces
This is a good callout.  I'll update the README to include an ansible-navigator example as well.

2022-06-07 22:28 UTC, tonyreveal commented on examples/README.md
> +An optional section for the role authors to include contact information, or a website (HTML is not allowed).
Sure.

2022-06-08 08:15 UTC, Tompage1994 commented on examples/pah_configure.yml
> +        - never
Yes, thats my point. I think you should be able to run without tags and do everything. Otherwise running without tags does nothing. By removing `never` and `alltags` you can still specify one tag (e.g. `users`) and it'll do just that. I think thats slightly better functionality

2022-06-08 08:15 UTC, Tompage1994 commented on examples/README.md
> +If executed with the `alltags` tag then the playbook will create all ojbects defined in all vars files in the appropriate order.
Just a typo thats highlighted with `ojbects` vs `objects`

2022-06-08 12:19 UTC, tonyreveal commented on examples/pah_configure.yml
> +        - never
Except that it was requested by a number of people to be written this way.  Do nothing unless a tag is passed.  I'm flexible.  I'm just explaining why it's written this way.

2022-06-08 13:03 UTC, djdanielsson commented on examples/pah_configure.yml
> +        - never
I agree with Tom, if no tags are provided I think the expected result should be do everything.

2022-06-08 13:15 UTC, tonyreveal commented on examples/pah_configure.yml
> +        - never
The change is made but I haven't pushed it.

2022-06-08 21:37 UTC, tonyreveal commented
I believe I've made all of the requested changes.  It looks like the github action requires an approval to run.

2022-06-08 21:47 UTC, Tompage1994 commented
I've kicked off the CI checks. I'll give it a review in the morning

2022-06-09 08:31 UTC, Tompage1994 requested changes
Just two small README changes.

When running its all good, though by having all the vars files with blank values it causes it to actually do things and fail in those modules. I wonder whether they should be set either as `[]` and have the options commented out or better yet have a full working demo example for each with bits that tie together? Happy to be left to the user though

2022-06-09 08:31 UTC, Tompage1994 commented on examples/README.md
> +If executed with the `alltags` tag then the playbook will create all objects defined in all vars files in the appropriate order.
I think this line can be removed now as `alltags` is gone

```suggestion

```

2022-06-09 08:31 UTC, Tompage1994 commented on examples/README.md
> +NOTE: If you do not specify any tags then no content will be created or updated.
Again, this line can be removed now.

```suggestion

```

2022-06-09 13:01 UTC, tonyreveal commented on examples/README.md
> +If executed with the `alltags` tag then the playbook will create all objects defined in all vars files in the appropriate order.
Fixed.  Will push shortly

2022-06-09 13:01 UTC, tonyreveal commented on examples/README.md
> +NOTE: If you do not specify any tags then no content will be created or updated.
Fixed.  Will push shortly

2022-06-14 16:36 UTC, djdanielsson approved these changes
I think you fixed all the things that have been requested. I will let @Tompage1994 merge if he is good with everything now.

2022-06-14 16:41 UTC, Tompage1994 approved these changes

2022-06-14 16:41 UTC, merged