rewrite of repository role
redhat-cop/ah_configuration pull request #124
Opened 2022-07-07 13:25 UTC by djdanielsson

### What does this PR do?
After thinking about this for a while, because hub only allows for 2 repos I am not sure if the loop is the best way to go about it. So this is my suggested rewrite and open for feedback on the idea.

### How should this be tested?
Automated tests should be fine

### Is there a relevant Issue open for this?
NA

### Other Relevant info, PRs, etc.
#120 would need to be merged first

2022-07-07 13:26 UTC, djdanielsson commented
@Tompage1994 I am interested in hearing your thoughts on this

2022-07-07 13:38 UTC, Tompage1994 commented
I very much get the premise behind this. I wonder whether there will ever be more repositories possible than rh-certified and community. I'm sure I remember some mention of abiltiies for promotion processes or similar to other AH instances on the roadmap which may happen through a repository endpoint. 

@sean-m-sullivan do you have any insight into this?

2022-07-07 13:47 UTC, Tompage1994 requested changes

2022-07-07 13:47 UTC, Tompage1994 commented on roles/repository/README.md
>  ## Variables
You'll need to mention

`ah_repository_certified` abd `ah_repository_community` here

2022-07-07 13:47 UTC, Tompage1994 commented on roles/repository/tasks/main.yml
> +    rate_limit:           "{{ ah_repository_certified['rate_limit'] | default(8) }}"
I assume these are all meant to be `ah_repository_community`

2022-07-07 13:52 UTC, djdanielsson commented on roles/repository/tasks/main.yml
> +    rate_limit:           "{{ ah_repository_certified['rate_limit'] | default(8) }}"
ooops, yep that is what i get for copy and pasting

2022-07-07 13:52 UTC, djdanielsson commented on roles/repository/README.md
>  ## Variables
Ok I made a note about it, let me know if you think it should be changed or could be more clear

2022-07-07 13:55 UTC, Tompage1994 requested changes

2022-07-07 13:55 UTC, Tompage1994 commented on roles/repository/README.md
> +These are the sub options for the vars ah_repository_certified and ah_repository_community which are dictionaries with the options you want. See examples for details.
```suggestion
These are the sub options for the vars `ah_repository_certified` and `ah_repository_community` which are dictionaries with the options you want. See examples for details.
```

2022-07-07 13:55 UTC, Tompage1994 commented on roles/repository/README.md
>  ## Variables
Looks good. Just added one suggestion to make it look a little nicer

2022-07-07 14:22 UTC, Tompage1994 reviewed
In terms of the content here, I think this is good to go.

The question remains whether we want to accept this PR. I think for now this is good, but as I say, I have concerns we may need to backtrack in the future. @sean-m-sullivan I'll leave it in your hands

2022-07-07 14:58 UTC, sean-m-sullivan commented
@Tompage1994 That was my thought as well, we might have to add another one in the future, I don't think there will ever be something like Job templates where it is 20 of them, but in the end 3 or 4 at most ever. David Posted this to me earlier, I'd say if you approved of it Tom, that we could merge, I'm on the fence, but not against the change.

2022-07-07 16:21 UTC, djdanielsson commented
because each repo will have its own specific options that only work for that name i think it makes more since to split it up like this then try and have the user understand it and correctly put it in a loop. it should also help with errors being a little more clear hopefully.

2022-07-07 17:10 UTC, Tompage1994 requested changes
Ok, I'm happy.

Could you add a changelog to this though and make it set as a breaking_change

2022-07-07 17:17 UTC, djdanielsson commented
would it be a breaking change since we haven't actually released a version with this role yet?

2022-07-07 21:30 UTC, djdanielsson commented
also another thought I had, should I make the sync role mirror this new layout? and if what are your thoughts on making an option so it could call the sync from this role as well? @Tompage1994 @sean-m-sullivan

2022-07-08 08:48 UTC, Tompage1994 commented
> would it be a breaking change since we haven't actually released a version with this role yet?

Its a breaking change to a previous version, so yes, I would say so. It's still worth being in the changelog as we should document properly what breaks when moving between versions

2022-07-08 08:52 UTC, Tompage1994 commented
> also another thought I had, should I make the sync role mirror this new layout? and if so, what are your thoughts on making an option so it could call the sync from this role as well? @Tompage1994 @sean-m-sullivan

The sync role could definitely follow this track. I suppose it can't hurt to call the sync role from this role too if a `.sync` option is provided. I'd suggest all this to be a separate PR and separate issue

2022-07-08 13:19 UTC, Tompage1994 approved these changes

2022-07-08 13:19 UTC, merged