fixing some repository role issues and updating repository sync role
redhat-cop/ah_configuration pull request #128
Opened 2022-07-08 18:13 UTC by djdanielsson

### What does this PR do?
fixes some repository role issues and updating repository sync role to match new repository role

### How should this be tested?
Manual test should be done once to insure everything works as expected.

### Is there a relevant Issue open for this?
none

### Other Relevant info, PRs, etc.
#124

2022-07-08 18:17 UTC, djdanielsson commented
One thing that might need to be checked before merging if https://github.com/redhat-cop/ah_configuration/blob/05d38867acf94a46b9823059664d62d5f1e4dfb3/roles/repository/tasks/main.yml#L6 is correct. Also I wanted to note the reason why these are not async tasks because I found in my testing that it would fail, to make up for this I defaulted wait to false so the task wouldn't take long.

2022-07-11 09:57 UTC, Tompage1994 requested changes

2022-07-11 09:57 UTC, Tompage1994 commented on roles/repository/README.md
> +|`url`|"cloud.redhat or galaxy"|no|Remote URL for the repository.|"https://galaxy.ansible.com/api/"|
This isn't the default for ah_repository_certified. Maybe we need a separate column here for the default for each?

2022-07-11 09:57 UTC, Tompage1994 commented on roles/repository/tasks/main.yml
>      username:             "{{ ah_repository_community['username'] | default(omit) }}"
Just realised we are missing a load of options here. E.g. auth_url and the cert stuff. I know by default we aren't authenticating against galaxy but there is always potential we might not be pointing at galaxy.ansible.com and instead at something else that may need auth. It's an option we can set in the UI so it should be an option we can set here (Obvioiusly set to `default(omit)`)

2022-07-11 09:57 UTC, Tompage1994 commented on roles/repository_sync/tasks/main.yml
> +# - name: Sync Automation Hub repository
Definitely shouldn't have this commented code

2022-07-11 09:57 UTC, Tompage1994 commented on roles/repository_sync/tasks/main.yml
> +    _community: "{{ lookup('template', 'community.j2') }}"
This is nasty. I really don't like this. It would just be better to play out both tasks as their own bit rather than hacking around to get it one task with a loop. The `item=...` message would be horrendous on this I imagine.

2022-07-11 09:57 UTC, Tompage1994 commented on roles/repository_sync/defaults/main.yml
> +# ah_configuration_repository_syncs_async_retries: "{{ ah_configuration_async_retries | default(50) }}"
Please don't just leave commented out stuff in here

2022-07-11 09:58 UTC, Tompage1994 commented
> 

I guess it fails because it takes ages. We could obviously default the retries to a much higher number?

2022-07-11 13:02 UTC, djdanielsson commented
no it instantly fails for me

2022-07-11 13:02 UTC, djdanielsson commented on roles/repository_sync/defaults/main.yml
> +# ah_configuration_repository_syncs_async_retries: "{{ ah_configuration_async_retries | default(50) }}"
i left the async stuff commented in if we figured out how to get it working

2022-07-11 13:03 UTC, djdanielsson commented on roles/repository_sync/tasks/main.yml
> +    _community: "{{ lookup('template', 'community.j2') }}"
the item looks normal it will return either certified or community i am pretty sure

2022-07-11 13:04 UTC, djdanielsson commented on roles/repository_sync/tasks/main.yml
> +# - name: Sync Automation Hub repository
the async code wasn't working for me which is why it is all commented out

2022-07-11 13:05 UTC, djdanielsson commented on roles/repository/tasks/main.yml
>      username:             "{{ ah_repository_community['username'] | default(omit) }}"
according to the UI there is no auth_url for community. I believe I have all the options that are in the UI for each type.

2022-07-11 13:06 UTC, djdanielsson commented on roles/repository/README.md
> +|`url`|"cloud.redhat or galaxy"|no|Remote URL for the repository.|"https://galaxy.ansible.com/api/"|
that is why i said in default value it was either cloud.redhat or galaxy and the example was the full url to show that but i understand that isn't the most clear. I wasn't sure how to make it clear having 2 of the same lines though

2022-07-11 13:34 UTC, djdanielsson commented on roles/repository_sync/tasks/main.yml
> +    _community: "{{ lookup('template', 'community.j2') }}"
TASK [redhat_cop.ah_configuration.repository_sync : Sync Automation Hub repository] **********************************************************************************************************************************************************
changed: [hub] => (item={'name': 'rh-certified'}) => {"__repository_item": {"name": "rh-certified"}, "ansible_loop_var": "__repository_item", "changed": true, "task": "bc75a278-6632-4e55-bae8-eadb7a70f0dd"}
changed: [hub] => (item={'name': 'community'}) => {"__repository_item": {"name": "community"}, "ansible_loop_var": "__repository_item", "changed": true, "task": "7ab8727a-830c-43f2-9aa4-d774e865853e"}

2022-07-11 13:58 UTC, Tompage1994 commented on roles/repository_sync/tasks/main.yml
> +    _community: "{{ lookup('template', 'community.j2') }}"
Oh, you're right.

Either way, I really don't like the fact you use a template to build out the options for a module. Couldn't you just do it by setting vars and then do a lookup using the `vars` lookup?

2022-07-11 14:31 UTC, djdanielsson commented on roles/repository_sync/tasks/main.yml
> +    _community: "{{ lookup('template', 'community.j2') }}"
If you have a better way then please post an example, this was the only way I could think of that wouldn't get set as "" because omit doesn't work outside of modules.

2022-07-11 14:53 UTC, Tompage1994 commented on roles/repository/tasks/main.yml
>      username:             "{{ ah_repository_community['username'] | default(omit) }}"
You're right. Not sure what happens if you set it with the api. That said you can definitely set client_key etc. in there so that should be added

2022-07-11 14:53 UTC, Tompage1994 commented on roles/repository/README.md
> +|`url`|"cloud.redhat or galaxy"|no|Remote URL for the repository.|"https://galaxy.ansible.com/api/"|
Yes, but the the user won't see exactly what the default really is. We should put the full values in there

2022-07-11 14:53 UTC, Tompage1994 commented on roles/repository_sync/tasks/main.yml
> +    _community: "{{ lookup('template', 'community.j2') }}"
What about something like this:

```
---
- name: Sync Automation Hub repository
  ah_repository_sync:
    name:           "{{ __repository_item.name }}"
    wait:           "{{ __repository_item.wait | default(false)  }}"
    interval:       "{{ __repository_item.interval | default(1) }}"
    timeout:        "{{ __repository_item.timeout | default(omit) }}"
    ah_host:        "{{ ah_host | default(ah_hostname) }}"
    ah_username:    "{{ ah_username | default(omit) }}"
    ah_password:    "{{ ah_password | default(omit) }}"
    ah_path_prefix: "{{ ah_path_prefix | default(omit) }}"
    ah_verify_ssl:  "{{ ah_validate_certs | default(omit) }}"
  when: _ah_repositories != []
  loop: "{{ _ah_repositories }}"
  loop_control:
    loop_var: "__repository_item"
  no_log: "{{ ah_configuration_repository_secure_logging }}"
  vars:
    ansible_async_dir: '/tmp/.ansible_async'
    _ah_repositories:
      - "{{ ah_repository_certified }}"
      - "{{ ah_repository_community }}"
```

2022-07-11 15:00 UTC, djdanielsson commented on roles/repository/tasks/main.yml
>      username:             "{{ ah_repository_community['username'] | default(omit) }}"
I think I have that... I just looked at the file in this commit and both tasks have client_key

2022-07-11 15:18 UTC, djdanielsson commented on roles/repository_sync/tasks/main.yml
> +    _community: "{{ lookup('template', 'community.j2') }}"
but I have to add .name to these lists so this wouldn't work

2022-07-11 15:20 UTC, djdanielsson commented on roles/repository_sync/tasks/main.yml
> +    _community: "{{ lookup('template', 'community.j2') }}"
I can try and see if i can get something like this to work but I don't know if it will
```
  vars:
    ansible_async_dir: '/tmp/.ansible_async'
    _ah_repositories:
      - "{{ ah_repository_certified + {'name': 'rh-certified'} }}"
      - "{{ ah_repository_community + {'name': 'community'} }}"
```

2022-07-11 15:23 UTC, Tompage1994 commented on roles/repository/tasks/main.yml
>      username:             "{{ ah_repository_community['username'] | default(omit) }}"
Ugh... ignore me. The diff didn't expand properly the last time I viewed the file

2022-07-11 15:30 UTC, Tompage1994 commented on roles/repository_sync/tasks/main.yml
> +    _community: "{{ lookup('template', 'community.j2') }}"
Good point...

This should do the trick

```
_ah_repositories:
          - "{{ ah_repository_certified | combine({'name': 'rh_certified'}) }}"
          - "{{ ah_repository_community | combine({'name': 'community'}) }}"
```

2022-07-11 15:31 UTC, Tompage1994 commented on roles/repository_sync/tasks/main.yml
> +    _community: "{{ lookup('template', 'community.j2') }}"
And you can deal with the loop label as such:

```
      loop: "{{ _ah_repositories }}"
      loop_control:
        loop_var: "__repository_item"
        label: "{{ __repository_item.name }}"
      vars:
        ansible_async_dir: '/tmp/.ansible_async'
        _ah_repositories:
          - "{{ ah_repository_certified | combine({'name': 'rh_certified'}) }}"
          - "{{ ah_repository_community | combine({'name': 'community'}) }}"
```

2022-07-11 17:35 UTC, djdanielsson commented on roles/repository_sync/tasks/main.yml
> +    _community: "{{ lookup('template', 'community.j2') }}"
I am still working on this, it looks like it should work fine but I am getting an error so trying to understand why.

2022-07-11 17:35 UTC, djdanielsson commented on roles/repository_sync/defaults/main.yml
> +# ah_configuration_repository_syncs_async_retries: "{{ ah_configuration_async_retries | default(50) }}"
I can delete if you really want

2022-07-11 17:48 UTC, djdanielsson commented on roles/repository/README.md
> +|`url`|"cloud.redhat or galaxy"|no|Remote URL for the repository.|"https://galaxy.ansible.com/api/"|
take a look and see if you think this looks good now

2022-07-11 19:34 UTC, djdanielsson commented
also should we update the default on no_log to true for this because it will show the full cloud token in the output which should be considered confidential

2022-07-12 09:06 UTC, Tompage1994 requested changes
Looking much better. Just tiny things now and one question.

2022-07-12 09:06 UTC, Tompage1994 commented on roles/repository/tasks/main.yml
> -    url:                  "{{ ah_repository_certified['url'] | default('https://cloud.redhat.com/api/automation-hub/') }}"
Why have you removed this default? Does this URL not work anymore?

2022-07-12 09:06 UTC, Tompage1994 commented on roles/repository/README.md
>  |`signed_only`|""|no|Only download signed collections|True|
Some of the boolean values are defaulted to false here. Could you update. E.g. `signed_only` defaults to false.

2022-07-12 13:00 UTC, djdanielsson commented on roles/repository/tasks/main.yml
> -    url:                  "{{ ah_repository_certified['url'] | default('https://cloud.redhat.com/api/automation-hub/') }}"
That is my question, it didn't seem to work so that is why I removed it. If it does still work I will put it back in

2022-07-12 13:39 UTC, Tompage1994 commented on roles/repository/tasks/main.yml
> -    url:                  "{{ ah_repository_certified['url'] | default('https://cloud.redhat.com/api/automation-hub/') }}"
Just tried doing a sync with `https://cloud.redhat.com/api/automation-hub/` in AH and it does work, so I would say leave that as default, then if a user wants to use a synclist they can

2022-07-12 14:28 UTC, djdanielsson commented on roles/repository/README.md
>  |`signed_only`|""|no|Only download signed collections|True|
I think I got them all defaulted now

2022-07-12 14:28 UTC, djdanielsson commented on roles/repository/tasks/main.yml
> -    url:                  "{{ ah_repository_certified['url'] | default('https://cloud.redhat.com/api/automation-hub/') }}"
cool, added back in

2022-07-12 15:10 UTC, Tompage1994 approved these changes
I'm happy with this now I think 👍

2022-07-12 15:11 UTC, Tompage1994 commented
Would be good if @sean-m-sullivan could give it a once over to make sure everything looks good here

2022-07-13 17:07 UTC, sean-m-sullivan approved these changes
LGTM

2022-07-13 17:07 UTC, merged