Testing Update
redhat-cop/ah_configuration pull request #141
Opened 2022-08-12 01:56 UTC by sean-m-sullivan

### What does this PR do?
FINALLY!!!!!!!!!!!!!!!!!!!
the ci test works for testing things. For the first time EVER!!!!!!!!!!!!!!!
Stuffs broken, but we have a working galaxy instance to test it against.

### How should this be tested?
it is the testing...

### Is there a relevant Issue open for this?
I thought there was one, but I can't find it.

2022-08-12 01:57 UTC, sean-m-sullivan commented
Note, this is pulled from here, they added some CI builds and there a few of them, I'm going to inquire about which does which that we can incorporate :)
https://github.com/ansible/galaxy_ng/blob/master/.github/workflows/ci_standalone.yml

2022-08-12 02:27 UTC, djdanielsson approved these changes
Even if it fails currently it is an improvement so I am approving it

2022-08-15 09:09 UTC, Tompage1994 requested changes
Happy with this as a start. There is one small question in here about the platform setup, but everything else looks good to go.

2022-08-15 09:09 UTC, Tompage1994 commented on .github/workflows/ci_standalone.yml
> +        run: sed -i.bak 's/PULP_GALAXY_REQUIRE_CONTENT_APPROVAL/#PULP_GALAXY_REQUIRE_CONTENT_APPROVAL/' galaxy_ng/dev/standalone/galaxy_ng.env
Should we not leave this in? Won't we want to test the functionality of approval as this is default behaviour anyway?

2022-08-15 13:15 UTC, djdanielsson commented on .github/workflows/ci_standalone.yml
> +        run: sed -i.bak 's/PULP_GALAXY_REQUIRE_CONTENT_APPROVAL/#PULP_GALAXY_REQUIRE_CONTENT_APPROVAL/' galaxy_ng/dev/standalone/galaxy_ng.env
that is actually a good point, I do think we need to test the approval functionality because we have had reported issues recently about that

2022-08-15 13:36 UTC, sean-m-sullivan commented on .github/workflows/ci_standalone.yml
> +        run: sed -i.bak 's/PULP_GALAXY_REQUIRE_CONTENT_APPROVAL/#PULP_GALAXY_REQUIRE_CONTENT_APPROVAL/' galaxy_ng/dev/standalone/galaxy_ng.env
I'm thinking we should test both deployments, We can remove for now, but I'm thinking we should have both approval and non approval.

2022-08-15 13:47 UTC, sean-m-sullivan commented on .github/workflows/ci_standalone.yml
> +        run: sed -i.bak 's/PULP_GALAXY_REQUIRE_CONTENT_APPROVAL/#PULP_GALAXY_REQUIRE_CONTENT_APPROVAL/' galaxy_ng/dev/standalone/galaxy_ng.env
Done

2022-08-15 14:31 UTC, Tompage1994 approved these changes

2022-08-15 14:32 UTC, merged