added ah_token to repository_sync role
redhat-cop/ah_configuration pull request #147
Opened 2022-09-12 20:36 UTC by gearboxscott

### What does this PR do?
added the `ah_token` to the `repository_sync` role `tasks/main.yml`, that was missing.  When reading the example in the README.md for the role and in the `tasks/main` itself, it mentions using `ah_token`.  If you use `ah_token` it will not reload a new token in the Private Automation Hub for the `admin` or any other user account.  This will allow prevent reload of a token that will break job templates and projects in Ansible Automation Hub because the token was changed. 

### How should this be tested?
We're just adding the missing variable that was omitted from the original code.  Adding the `ah_token:` to the `ah_auth.yml` in the `ah_config` directory with the current token should allow this role to run as intended originally per the original example.

### Is there a relevant Issue open for this?
n/a, just fixed it.

### Other Relevant info, PRs, etc.
n/a

2022-09-12 22:07 UTC, djdanielsson requested changes
please fix changelogs and then I will approve

2022-09-12 22:07 UTC, djdanielsson commented on changelogs/fragments/collection.yml
> +  - add `ah_token` so repository_sync works with token only and doesn't change the original token that happens when using `ah_username` and `ah_password`. This will keep it from breaking Ansible Auto
create new line do not delete someone else's change. also please shorten to:

add `ah_token` so repository_sync that was missing

2022-09-13 06:19 UTC, gearboxscott commented on changelogs/fragments/collection.yml
> +  - add `ah_token` so repository_sync works with token only and doesn't change the original token that happens when using `ah_username` and `ah_password`. This will keep it from breaking Ansible Auto
completed the requested changes

2022-09-13 13:23 UTC, djdanielsson approved these changes
small typo in changelog but that's ok, I found another issue I am working on a fix and I can correct it then. thanks for finding this issue and fixing it.

2022-09-13 13:23 UTC, merged