Draft: add ah token to auth ui doc fragment
redhat-cop/ah_configuration pull request #162
Opened 2022-10-06 14:12 UTC by sean-m-sullivan

### What does this PR do?

This should add the ah_token to multiple modules that are currently missing it. 

modules include this file like so
https://github.com/redhat-cop/ah_configuration/blob/devel/plugins/modules/ah_user.py#L79

2022-10-06 14:22 UTC, djdanielsson approved these changes
hopefully this will fix #163

2022-10-06 14:32 UTC, ivarmu approved these changes
LGTM

2022-10-06 14:32 UTC, silvinux approved these changes
LGTM. Nice catch!

2022-10-06 14:47 UTC, djdanielsson requested changes
waiting for confirmation that this does fix the issue before approving and merging

2022-10-06 14:53 UTC, ivarmu commented
This is (by now) only a documentation fragment addition... this won't solve nothing at all:

![image](https://user-images.githubusercontent.com/26822043/194345830-4db82d82-b3b1-49ea-88c9-106eaa646949.png)

2022-10-06 15:09 UTC, sean-m-sullivan commented
This needs more so WIP

2022-10-07 07:38 UTC, ivarmu commented
Just to give some information:

When authenticating with `username` and `password`, the endpoint to be used seems to be `/api/galaxy/_ui/v1/auth/login/`.
When authenticating with `token`, the enpoint to be used seems to be `/api/galaxy/v3/auth/token/`.

2022-12-08 15:01 UTC, djdanielsson commented
@sean-m-sullivan should we close this?

2022-12-08 17:17 UTC, closed without merging