Fix version comparison
redhat-cop/ah_configuration pull request #335
Opened 2023-11-16 17:59 UTC by rochacbruno

Compara versions using packaging.version.Version

closes #334

2023-11-16 18:02 UTC, rochacbruno commented
packaging is added by ansible https://github.com/ansible/ansible/blob/devel/requirements.txt#L9

Not sure why the CI is failing, do we need to include it elsewhere?

2023-11-16 18:43 UTC, sean-m-sullivan approved these changes
Clean, thanks!

2023-11-16 19:40 UTC, rochacbruno commented
@sean-m-sullivan CI is failing because the packaging dependency cannot be found

2023-11-17 01:55 UTC, sean-m-sullivan commented
it looks like this dependency is not part of the ansible install. need it in requirements.txt in the base directory.

2023-11-17 09:15 UTC, rochacbruno commented
ALternativelly we can create our own implementation of the class `Version` and not depend on external library.

```python
class Version:
    def __init__(self, version_str):
        components = list(map(int, version_str.split('.')))
        self.major = components[0]
        self.minor = components[1] if len(components) > 1 else 0
        self.patch = components[2] if len(components) > 2 else 0

    def __str__(self):
        return f"{self.major}.{self.minor}.{self.patch}"

    def __eq__(self, other):
        if not isinstance(other, Version):
            return NotImplemented
        return (self.major, self.minor, self.patch) == (other.major, other.minor, other.patch)

    def __lt__(self, other):
        if not isinstance(other, Version):
            return NotImplemented
        return (self.major, self.minor, self.patch) < (other.major, other.minor, other.patch)

    def __le__(self, other):
        if not isinstance(other, Version):
            return NotImplemented
        return (self < other) or (self == other)

    def __gt__(self, other):
        if not isinstance(other, Version):
            return NotImplemented
        return not (self <= other)

    def __ge__(self, other):
        if not isinstance(other, Version):
            return NotImplemented
        return not (self < other)

    def __ne__(self, other):
        if not isinstance(other, Version):
            return NotImplemented
        return not (self == other)

# Example usage:
version1 = Version("4.2")
version2 = Version("5.1.3")

print(version1 < version2)  # Output: True
print(version1 >= version2)  # Output: False

```

2023-11-17 14:00 UTC, Tompage1994 requested changes

2023-11-17 14:00 UTC, Tompage1994 commented on plugins/modules/ah_ee_image.py
> +from ansible.module_utils.compat.version import LooseVersion as Version
sanity check is stating that this needs to be with the imports further down below the documentation segment

2023-11-17 14:00 UTC, Tompage1994 commented on plugins/modules/ah_ee_image.py
> +from ansible.module_utils.compat.version import LooseVersion as Version
Plus the same for all the other modules

2023-11-17 14:44 UTC, rochacbruno commented
Trying a simpler implementation on https://github.com/ansible/galaxy_collection/pull/337

2023-11-17 14:55 UTC, rochacbruno commented
Closing in favor of #337

2023-11-17 14:55 UTC, closed without merging