update infra release branch for release
redhat-cop/ah_configuration pull request #369
Opened 2024-03-20 14:18 UTC by sean-m-sullivan

update infra release branch for release

2024-03-20 22:35 UTC, djdanielsson requested changes
I had one question that is repeated throughout

2024-03-20 22:35 UTC, djdanielsson commented on roles/collection_remote/tasks/main.yml
> +    ah_host:                  "{{ ah_host | default(ah_hostname) | default(omit) }}"
I might have missed it but what case would ah_host be omitted?

2024-03-21 20:38 UTC, sean-m-sullivan commented on roles/collection_remote/tasks/main.yml
> +    ah_host:                  "{{ ah_host | default(ah_hostname) | default(omit) }}"
Found it here, legit changed
https://github.com/ansible/galaxy_collection/pull/363

2024-03-25 11:12 UTC, Tompage1994 approved these changes

2024-03-26 14:34 UTC, closed without merging