Add collection manage plugin
redhat-cop/ah_configuration pull request #61
Opened 2022-02-15 05:26 UTC by sean-m-sullivan

### What does this PR do?
Add a collection manage plugin
        - If present will return data on a collection.
        - If present with version, will return data on a collection version.
        - If absent without version, will delete the collection and all versions.
        - If absent with version, will delete only specified version.

### How should this be tested?
Automated tests

I wonder if I should merge in the functionality of ah_collection_upload to this, Upload if specified path, then get its data, and delete if state is absent.

2022-02-15 17:58 UTC, Tompage1994 requested changes
I like this. I haven't had a chance to test but will do before merging. 

I do think we should add the functionality of collection_upload into this and simply have one `ah_collection` module which does both things. I don't think it entirely makes sense to have `state: present` not actually cause an action (other than return data) since that doesn't fit in with creating a desired state. I would essentially just take the `ah_collection_upload` module and add the ability to delete collections. In other words `path` will probably be a required option when state == present

2022-02-15 17:58 UTC, Tompage1994 commented on plugins/modules/ah_collection_manage.py
> +module: ah_collection_manage
Not sure `_manage` fits in with usual naming for a module. This should potentially just be `ah_collection`

2022-02-15 18:34 UTC, sean-m-sullivan commented on plugins/modules/ah_collection_manage.py
> +module: ah_collection_manage
With the addition of the upload yes, I was trying to make it so it was differentiated.

2022-02-15 18:36 UTC, sean-m-sullivan commented on plugins/modules/ah_collection_manage.py
> +module: ah_collection_manage
Also thinking its going to be good to return the data anyways once its created, for reference, The data part, was more to have Something returned, why not get the collection data.

2022-02-16 05:15 UTC, sean-m-sullivan commented
updated to make the changes, integrate publish, and make it so it does best of both

2022-02-16 13:47 UTC, Tompage1994 requested changes

2022-02-16 13:47 UTC, Tompage1994 commented on plugins/modules/ah_collection.py
> +  ah_collection_upload:
Should we not just remove the collection upload module completely?

2022-02-16 15:57 UTC, Tompage1994 requested changes
This flow doesn't quite work if you specify the version and the path as the collection is awaiting approval and you get a failure of the task.

I think you should also do the check on version first to see if item exists, and if so then don't bother with attempting upload.

2022-02-16 15:58 UTC, Tompage1994 commented
> This flow doesn't quite work if you specify the version and the path as the collection is awaiting approval and you get a failure of the task.
> 
> I think you should also do the check on version first to see if item exists, and if so then don't bother with attempting upload.

`ansible -m  redhat_cop.ah_configuration.ah_collection -a "path=redhat_cop-ah_configuration-0.0.1-test.tar.gz namespace=redhat_cop name=ah_configuration version='0.0.1-test'" localhost -c local` fails with:

```
localhost | FAILED! => {
    "changed": false,
    "msg": "Could not find Collection redhat_cop.ah_configuration with_version 0.0.1-test"
}
```

despite the collection having uploaded and awaiting approval

2022-02-16 15:59 UTC, Tompage1994 commented
I wonder also if we should add the ability to auto-approve the collection in here too then implement the functionality of the ah_approval module here too.

2022-03-01 03:11 UTC, sean-m-sullivan commented
@Tompage1994 Reworked for workflow, also added an override, so it can just force a new version if the user wants by using the delete, and reworked the entire flow, to incorporate the approval and override.

2022-03-01 09:31 UTC, Tompage1994 reviewed
Will give a proper review later when I get time

2022-03-01 09:31 UTC, Tompage1994 commented on plugins/module_utils/ah_module.py
> +            time.sleep(1)
I was going to complain about this, and perhaps we could do something such as provide an option for 'interval' and 'timeout' but I see this is exaclty what our friends in awx.awx do so I guess this is fine.

2022-03-01 15:33 UTC, sean-m-sullivan commented on plugins/module_utils/ah_module.py
> +            time.sleep(1)
I think I put in the sleep as between when it would upload, and the api would be populated it needed a second. Its for after the collection upload, not for waiting on it to be uploaded :)

2022-03-02 16:55 UTC, Tompage1994 requested changes
Quite a few things and we are a fair way off accepting this

2022-03-02 16:55 UTC, Tompage1994 commented on plugins/modules/ah_collection.py
> +    state: absent
This doesnt work. If you add in a version you get the following:

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to approve at collections/redhat_cop/ah_configuration/versions/0.0.8-dev: Awaiting approval not found"}`

2022-03-02 16:55 UTC, Tompage1994 commented on plugins/modules/ah_collection.py
> +"""
Also 
```
- redhat_cop.ah_configuration.ah_collection:
        namespace: redhat_cop
        name: ah_configuration
        state: absent
        ah_host: https://localhost:8443
        ah_username: admin
        ah_password: password
        validate_certs: false
```

gives

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find Collection redhat_cop.ah_configuration"}` when the collection isnt there

2022-03-02 16:55 UTC, Tompage1994 commented on plugins/modules/ah_collection.py
> +      default: true
It seems the behaviour I've seen is that it defaults to false?

2022-03-02 16:55 UTC, Tompage1994 commented on plugins/modules/ah_collection.py
> +      default: true
Actually, seeing that you need to set version too. That being said the version doesn't seem to really be used. We could work out the version based on whats passed in (the old module did that)

2022-03-02 16:55 UTC, Tompage1994 commented on plugins/modules/ah_collection.py
> +    state: absent
i.e. not idempotent

2022-03-05 22:33 UTC, sean-m-sullivan commented on plugins/modules/ah_collection.py
> +"""
Fixed for multiple scenarios with absent

2022-03-05 22:38 UTC, sean-m-sullivan commented on plugins/modules/ah_collection.py
> +      default: true
Changed behavior to just approve after upload if its set to auto approve.

2022-03-05 22:39 UTC, sean-m-sullivan commented on plugins/modules/ah_collection.py
> +    state: absent
Fixed to be idempotent

2022-03-05 22:41 UTC, sean-m-sullivan commented
Sorry, busy week, Updated things, I think I've addressed the issues you found. I don't have an approval based AH atm, if you could test that? thanks

2022-03-14 17:17 UTC, Tompage1994 requested changes
Looks much better. One error-handling and one functional issue then all good.

2022-03-14 17:17 UTC, Tompage1994 commented on plugins/modules/ah_collection.py
> +        path=dict(),
Could we have a properly thrown error when the path is not found. I currently get a nasty stack trace if providing a path which is incorrect

2022-03-14 17:17 UTC, Tompage1994 commented on plugins/modules/ah_collection.py
> +    if path:
Also 

```
- redhat_cop.ah_configuration.ah_collection:
        namespace: redhat_cop
        name: ah_configuration
        version: 0.0.9-dev
        path: ../redhat_cop-ah_configuration-0.0.9-dev.tar.gz
        state: absent
        ah_host: https://localhost:8443
        ah_username: admin
        ah_password: password
        validate_certs: false
```
will upload the collection despite `state: absent`. Need to switch around this if statement here because if state is absent then things certainly shouldnt be created

2022-03-14 18:35 UTC, sean-m-sullivan commented on plugins/modules/ah_collection.py
> +    if path:
Moved state absent to be checked first and to exit module after its tasks.

2022-03-14 18:36 UTC, sean-m-sullivan commented on plugins/modules/ah_collection.py
> +        path=dict(),
Add a pathlib check as that is supposed to be the module to use in python 3.4, on state = present to check for a path.

2022-03-22 17:58 UTC, closed without merging