Sean m sullivan devel
redhat-cop/ah_configuration pull request #64
Opened 2022-03-15 14:07 UTC by sean-m-sullivan

### What does this PR do?
Add a collection manage plugin
        - If present will return data on a collection.
        - If present with version, will return data on a collection version.
        - If absent without version, will delete the collection and all versions.
        - If absent with version, will delete only specified version.

### How should this be tested?
Automated tests

I wonder if I should merge in the functionality of ah_collection_upload to this, Upload if specified path, then get its data, and delete if state is absent.

2022-03-22 09:29 UTC, Tompage1994 requested changes
One small change

2022-03-22 09:29 UTC, Tompage1994 commented on plugins/modules/ah_collection.py
> +              module.approve(
I've run across this before and I'm running into it now. The collection is uploaded but the awaiting approval isn't ready when it gets to the code for approval. I think it may be worth adding a loop around the module.approve here to wait up to 5s or so for the approval to appear. (i.e. attempt approval and if fail sleep 1s). 

```
TASK [redhat_cop.ah_configuration.ah_collection] **********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to approve at collections/redhat_cop/ah_configuration/versions/0.0.9-dev: Awaiting approval not found"}
```
I can see following this that the collection is awaiting approval

2022-03-22 10:04 UTC, Tompage1994 commented
Also, does this supersede the other PR open?

2022-03-22 17:58 UTC, sean-m-sullivan commented on plugins/modules/ah_collection.py
> +              module.approve(
Ok, will work on this, and yes this does supersede the other PR, #61 Just linking it in here now for reference and closing it.

2022-03-28 16:19 UTC, Tompage1994 approved these changes

2022-03-28 16:19 UTC, merged